services:
  ros:
    build:
      context: .
      dockerfile: dockerfile
    container_name: ros_noetic

    devices:
      - /dev:/dev
      - /dev/bus/usb:/dev/bus/usb
    environment:
      - DISPLAY=192.168.31.54:0
      - ROS_MASTER_URI=http://192.168.31.60:11311
      - export ROS_IP=192.168.31.60
      - QT_X11_NO_MITSHM=1
      - LIBGL_ALWAYS_SOFTWARE="0"


    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY:-$HOME/.Xauthority}:/tmp/docker.xauth:ro
      - .:/ros_ws
    working_dir: /ros_ws

    network_mode: host
    privileged: true
    stdin_open: true
    tty: true
